# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008724715c5211a292c33d57debba8f1e5bfc33bd212c4ae2a10c07f93efcf5f3d6f51908516ba0773445b8c1f5c833197a07b6a6491581e255ff71039a264c8

test:
  secret_key_base: 34b21b79a128f821b0d37d8636e497f7addb556dd0323acc8a7da043ab0f76673d6dbb216731f4c2f9be1310630cbaf3ac6d8b992e72a6960ded1f59a26c27ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
